version: '3.6'
services:
  postgres:
    container_name: kaigen-postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - kaigen
    ports:
      - '5432:5432'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

networks:
  kaigen:
    name: kaigen-network
