version: '3.6'
services:
  # redis:
  #   container_name: kaigen-redis
  #   image: docker.io/bitnami/redis-cluster:7.0.8
  #   environment:
  #     - 'ALLOW_EMPTY_PASSWORD=yes'
  #     - 'REDIS_CLUSTER_REPLICAS=0'
  #     - 'REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1'
  #     - 'REDIS_CLUSTER_CREATOR=yes'
  #     - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
  #     - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
  #   networks:
  #     - kaigen
  #   ports:
  #     - '6379:6379'
  postgres:
    container_name: kaigen-postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - kaigen
    ports:
      - '5432:5432'

networks:
  kaigen:
    name: kaigen-network
